https://www.perplexity.ai/search/0ead468a-cad0-4bd6-8c76-b23fcd5773f4

In [ ]:
odd = [1, 3, 5, 7, 9]
even = [2, 4, 6, 8, 10]

#list使用`+`運算子(表示顯示全部元素)
odd + even

#如果要對元素作用,必需取出元素

[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]

In [4]:
import numpy as np

odd_array = np.array(odd)
even_array = np.array(even)

#ndarray使用'+'運算子
#ndarray ->陣列運算
#可省for...in迴圈
odd_array + even_array
odd_array * even_array
odd_array / even_array
even_array - odd_array 


array([1, 1, 1, 1, 1])

In [5]:
np.arange(5)
# 輸出: array([0, 1, 2, 3, 4])，從0開始到5（不含5），步長1

np.arange(1, 5)
# 輸出: array([1, 2, 3, 4])，從1開始到5（不含5），步長1

np.arange(1, 5, 2)
# 輸出: array([1, 3])，從1開始到5（不含5），步長2

np.arange(1, 5.2, 0.6)
# 輸出: array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6, 5.2])，浮點步長，注意可能包含大於stop的值

array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6, 5.2])

In [7]:
import numpy as np

# 產生0到1之間均勻分布的11個數值（包含0和1）
arr1 = np.linspace(0, 1, 11)
# 輸出: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

# 不包含終點，產生0到1之間10個數值
arr2 = np.linspace(0, 1, 10, endpoint=False)
# 輸出: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

# 同時返回數值序列與間距
arr3, step = np.linspace(0, 1, 5, retstep=True)
# arr3: [0.   0.25 0.5  0.75 1.  ]
# step: 0.25

# 指定資料型態為整數
arr4 = np.linspace(0, 10, 5, dtype=int)
# 輸出: [ 0  2  5  7 10]

In [8]:
np.linspace(0,1,5)
np.linspace(0,1,50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])