# ndarray的索引(index) ，切割(slice)

In [1]:
import numpy as np

arr = np.arange(10)
arr[0]
arr[-1]
arr[:3]
arr[-3:]

array([7, 8, 9])

In [2]:
import random
random.randint(50,100)

79

In [3]:
np.random.randint(50,101,size=5)
scores = np.random.randint(50,101,size=(50,5))
scores.size
scores.shape

(50, 5)

In [4]:
scores[:0] #一維
scores[:,0:1] #二維


array([[ 55],
       [ 58],
       [ 85],
       [ 89],
       [ 70],
       [ 50],
       [ 55],
       [ 76],
       [ 84],
       [ 86],
       [ 86],
       [ 81],
       [ 79],
       [ 55],
       [ 97],
       [ 88],
       [ 56],
       [ 67],
       [ 76],
       [ 94],
       [ 86],
       [ 62],
       [ 51],
       [ 59],
       [ 54],
       [ 66],
       [ 69],
       [ 50],
       [ 61],
       [ 81],
       [ 62],
       [ 73],
       [ 92],
       [ 73],
       [ 57],
       [ 69],
       [ 97],
       [ 58],
       [ 74],
       [ 50],
       [ 96],
       [ 81],
       [ 70],
       [ 89],
       [ 84],
       [ 54],
       [ 81],
       [100],
       [ 79],
       [ 81]], dtype=int32)

In [5]:
scores[0,:]
scores[0:1,:]

array([[55, 63, 86, 65, 91]], dtype=int32)

In [6]:
np.sum(scores,axis=1)
np.mean(scores, axis=1)

array([72. , 75.2, 81.6, 75. , 65. , 71.8, 73.6, 81. , 85.8, 81.2, 79.2,
       70.6, 79.4, 69.6, 76. , 85.8, 74.8, 79.4, 74.4, 62.6, 68. , 62.4,
       72.8, 75.4, 72.8, 72.8, 83. , 74.6, 70.4, 73.8, 70. , 73.6, 84.2,
       71. , 78.4, 65. , 75.6, 77. , 64.6, 67.8, 83.8, 77. , 78.2, 86.2,
       76. , 58. , 79.8, 75.6, 75. , 70.4])

In [ ]:
#使用比較運算子
arr = np.random.randn(5)
arr > 0 #大於零的為true


array([ True, False, False, False, False])

In [ ]:
np.where(arr > 0, 1, 0) #true是零

array([1, 0, 0, 0, 0])

In [ ]:
np.where(arr > 0, 1, arr) #小於零的寫出完整數值，大於零的視為一

array([ 1.        , -1.46862135, -0.45403445, -0.46726794, -0.65452853])