https://www.perplexity.ai/search/27854047-0059-44b3-b1ed-b6dbdddd6505

# numpy的索引和切割

In [2]:
import numpy as np
scores = np.random.randint(50,101,size=(5,5))
scores

array([[ 64,  88,  95,  97,  85],
       [ 69,  62,  82,  69,  96],
       [ 65,  96,  63,  59,  52],
       [ 87,  84,  77,  96, 100],
       [ 98,  58,  70,  80,  84]], dtype=int32)

In [3]:
scores[:3,2:]

array([[95, 97, 85],
       [82, 69, 96],
       [63, 59, 52]], dtype=int32)

In [6]:
scores[4]
scores[4,:]
scores[4:,:]

array([[98, 58, 70, 80, 84]], dtype=int32)

In [8]:
scores[:,2:]

array([[ 95,  97,  85],
       [ 82,  69,  96],
       [ 63,  59,  52],
       [ 77,  96, 100],
       [ 70,  80,  84]], dtype=int32)