https://www.perplexity.ai/search/27854047-0059-44b3-b1ed-b6dbdddd6505

### numpy的索引和切割

In [2]:
import numpy as np
scores = np.random.randint(50,101,size=(5,5))
scores

array([[ 64,  88,  95,  97,  85],
       [ 69,  62,  82,  69,  96],
       [ 65,  96,  63,  59,  52],
       [ 87,  84,  77,  96, 100],
       [ 98,  58,  70,  80,  84]], dtype=int32)

In [3]:
scores[:3,2:]

array([[95, 97, 85],
       [82, 69, 96],
       [63, 59, 52]], dtype=int32)

In [6]:
scores[4]
scores[4,:]
scores[4:,:]

array([[98, 58, 70, 80, 84]], dtype=int32)

In [8]:
scores[:,2:]

array([[ 95,  97,  85],
       [ 82,  69,  96],
       [ 63,  59,  52],
       [ 77,  96, 100],
       [ 70,  80,  84]], dtype=int32)

### numpy統計工具

In [9]:
scores = np.random.randint(50,101,size=(5,5))
scores

array([[66, 60, 68, 59, 69],
       [94, 51, 74, 58, 92],
       [89, 75, 85, 98, 80],
       [82, 95, 86, 96, 65],
       [52, 62, 84, 82, 58]], dtype=int32)

In [11]:
#加總
np.sum(scores,axis=1)#axis有零有一


array([322, 369, 427, 424, 338])

In [12]:
#平均
np.mean(scores, axis=1)


array([64.4, 73.8, 85.4, 84.8, 67.6])

In [13]:
#最大
np.max(scores,axis=1)


array([69, 94, 98, 96, 84], dtype=int32)

In [14]:
#最小
np.min(scores,axis=1)

array([59, 51, 75, 65, 52], dtype=int32)

In [15]:
#中間數
np.median(scores,axis=1)

array([66., 74., 85., 86., 62.])

In [16]:
#標準差
np.std(scores,axis=1)

array([ 4.12795349, 17.3712406 ,  7.8638413 , 11.23209687, 12.98614646])