https://www.perplexity.ai/search/1f6d8098-e981-44bf-b915-b14b9e9052da

In [1]:
import numpy as np
np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [ ]:
np.zeros((3, 4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [5]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [6]:
np.random.rand(3, 4)

array([[0.4015388 , 0.10478782, 0.75427081, 0.55662918],
       [0.96413949, 0.57381913, 0.52663573, 0.92903971],
       [0.37489405, 0.77646857, 0.53580621, 0.90234393]])

In [9]:
scores = np.random.randint(50,101,size=(50, 5))
scores

array([[ 99,  50,  97,  52,  72],
       [ 60,  98,  77,  96, 100],
       [ 83,  83,  72,  59,  66],
       [ 74,  80,  53,  99,  58],
       [ 57,  76,  53,  97,  83],
       [ 70,  70,  79,  61,  70],
       [ 62,  69,  62,  84,  96],
       [ 87,  70,  97,  77,  66],
       [ 59,  82,  54,  88,  59],
       [ 70,  67,  76,  93,  81],
       [ 87,  94,  79,  90,  74],
       [ 56,  51,  84,  83,  66],
       [ 53,  51,  85,  64,  66],
       [ 80,  94,  53,  77,  73],
       [ 86,  99,  77,  80,  97],
       [ 93,  51,  79,  50,  81],
       [ 63,  82,  71,  70,  71],
       [ 88,  84,  58,  96,  79],
       [ 93,  90,  68,  75,  87],
       [ 80,  77,  59,  92,  69],
       [ 67,  52,  94,  60,  58],
       [ 98,  91,  78,  61,  61],
       [ 55,  94,  68,  95,  94],
       [ 71,  59,  69,  59,  70],
       [ 79,  77,  80,  70,  82],
       [ 78,  86,  65,  75,  86],
       [ 52,  91,  99,  77,  71],
       [ 56,  88, 100,  78,  72],
       [ 50,  79,  77,  64,  50],
       [ 89,  